### ISSUE TITLE
[AIO-15] Product 도메인 구성을 위한 초안

### ISSUE THREAD

**Issue by boring-km** [chaibin0/all-in-one#10]
Product 객체를 사용하기 위한 도메인 초안
![도메인 초안](https://user-images.githubusercontent.com/34850203/91677739-98315d00-eb7e-11ea-8297-ecf28c0e6ffe.jpg)

**Comment by chaibin0** [comment]
꼭 product info에 합쳐야 할까?
ROOM, Vehicle, Store는 전부 분리해서 도메인을 만들어도 좋을거 같다고 생각함.

**Comment by boring-km** [comment]
합친거 아님

**Comment by boring-km** [comment]
mongoDB에 HouseProduct, StoreProduct, VehicleProduct 이렇게 Collection 3개 있으면 될듯
